[2024-10-14T17:30:45.172+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T17:30:46.216+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-04T00:00:00+00:00 [queued]>
[2024-10-14T17:30:47.197+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-04T00:00:00+00:00 [queued]>
[2024-10-14T17:30:47.299+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-14T17:30:49.251+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ccl_to_redshift> on 2024-09-04 00:00:00+00:00
[2024-10-14T17:30:51.928+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=19080) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T17:30:52.150+0000] {standard_task_runner.py:72} INFO - Started process 19129 to run task
[2024-10-14T17:30:52.136+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_ccl', 'ccl_to_redshift', 'scheduled__2024-09-04T00:00:00+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/dag_ccl.py', '--cfg-path', '/tmp/tmpifhy98j5']
[2024-10-14T17:30:52.311+0000] {standard_task_runner.py:105} INFO - Job 293: Subtask ccl_to_redshift
[2024-10-14T17:31:01.295+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-04T00:00:00+00:00 [running]> on host f03003374728
[2024-10-14T17:31:04.659+0000] {job.py:229} INFO - Heartbeat recovered after 29.01 seconds
[2024-10-14T17:31:26.251+0000] {job.py:229} INFO - Heartbeat recovered after 22.92 seconds
[2024-10-14T17:31:40.161+0000] {job.py:229} INFO - Heartbeat recovered after 18.07 seconds
[2024-10-14T17:32:01.058+0000] {job.py:229} INFO - Heartbeat recovered after 13.04 seconds
[2024-10-14T17:32:12.876+0000] {job.py:229} INFO - Heartbeat recovered after 12.08 seconds
[2024-10-14T17:32:23.867+0000] {job.py:229} INFO - Heartbeat recovered after 11.34 seconds
[2024-10-14T17:32:35.997+0000] {job.py:229} INFO - Heartbeat recovered after 12.28 seconds
[2024-10-14T17:32:52.952+0000] {job.py:229} INFO - Heartbeat recovered after 19.15 seconds
[2024-10-14T17:33:06.705+0000] {job.py:229} INFO - Heartbeat recovered after 16.41 seconds
[2024-10-14T17:33:17.201+0000] {job.py:229} INFO - Heartbeat recovered after 10.70 seconds
[2024-10-14T17:33:28.527+0000] {job.py:229} INFO - Heartbeat recovered after 11.43 seconds
[2024-10-14T17:33:28.889+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-10-14T17:33:31.765+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-14T17:33:33.034+0000] {process_utils.py:132} INFO - Sending 15 to group 19129. PIDs of all processes in the group: [19129]
[2024-10-14T17:33:34.043+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 19129
[2024-10-14T17:33:38.597+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=19129, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='17:30:51') (19129) terminated with exit code -15
[2024-10-14T17:33:41.913+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-10-16T14:41:10.407+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-16T14:41:10.446+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-04T00:00:00+00:00 [queued]>
[2024-10-16T14:41:10.456+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-04T00:00:00+00:00 [queued]>
[2024-10-16T14:41:10.456+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-16T14:41:10.518+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ccl_to_redshift> on 2024-09-04 00:00:00+00:00
[2024-10-16T14:41:10.534+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=146) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-16T14:41:10.539+0000] {standard_task_runner.py:72} INFO - Started process 160 to run task
[2024-10-16T14:41:10.547+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_ccl', 'ccl_to_redshift', 'scheduled__2024-09-04T00:00:00+00:00', '--job-id', '378', '--raw', '--subdir', 'DAGS_FOLDER/dag_ccl.py', '--cfg-path', '/tmp/tmp8z4jzhit']
[2024-10-16T14:41:10.558+0000] {standard_task_runner.py:105} INFO - Job 378: Subtask ccl_to_redshift
[2024-10-16T14:41:10.654+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-04T00:00:00+00:00 [running]> on host f03003374728
[2024-10-16T14:41:11.187+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ccl' AIRFLOW_CTX_TASK_ID='ccl_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-09-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-04T00:00:00+00:00'
[2024-10-16T14:41:11.190+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-16T14:41:11.275+0000] {logging_mixin.py:190} INFO - 2024-09-04
[2024-10-16T14:41:11.904+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-16T14:41:11.905+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-16T14:41:14.287+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-16T14:41:14.447+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-16T14:41:14.450+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_ccl, task_id=ccl_to_redshift, run_id=scheduled__2024-09-04T00:00:00+00:00, execution_date=20240904T000000, start_date=20241016T144110, end_date=20241016T144114
[2024-10-16T14:41:14.741+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-16T14:41:14.818+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-16T14:41:14.825+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
