[2024-10-14T17:30:46.159+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T17:30:48.651+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-08T00:00:00+00:00 [queued]>
[2024-10-14T17:30:51.203+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-08T00:00:00+00:00 [queued]>
[2024-10-14T17:30:51.548+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-14T17:30:52.744+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ccl_to_redshift> on 2024-09-08 00:00:00+00:00
[2024-10-14T17:30:55.256+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=19091) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T17:30:55.647+0000] {standard_task_runner.py:72} INFO - Started process 19140 to run task
[2024-10-14T17:30:55.331+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_ccl', 'ccl_to_redshift', 'scheduled__2024-09-08T00:00:00+00:00', '--job-id', '295', '--raw', '--subdir', 'DAGS_FOLDER/dag_ccl.py', '--cfg-path', '/tmp/tmprzfxn5vd']
[2024-10-14T17:30:56.125+0000] {standard_task_runner.py:105} INFO - Job 295: Subtask ccl_to_redshift
[2024-10-14T17:31:08.177+0000] {job.py:229} INFO - Heartbeat recovered after 25.24 seconds
[2024-10-14T17:31:09.877+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-08T00:00:00+00:00 [running]> on host f03003374728
[2024-10-14T17:31:26.236+0000] {job.py:229} INFO - Heartbeat recovered after 18.48 seconds
[2024-10-14T17:31:41.430+0000] {job.py:229} INFO - Heartbeat recovered after 17.02 seconds
[2024-10-14T17:31:53.739+0000] {job.py:229} INFO - Heartbeat recovered after 12.46 seconds
[2024-10-14T17:32:04.128+0000] {job.py:229} INFO - Heartbeat recovered after 10.84 seconds
[2024-10-14T17:32:23.677+0000] {job.py:229} INFO - Heartbeat recovered after 19.75 seconds
[2024-10-14T17:32:34.393+0000] {job.py:229} INFO - Heartbeat recovered after 11.12 seconds
[2024-10-14T17:32:49.649+0000] {job.py:229} INFO - Heartbeat recovered after 15.63 seconds
[2024-10-14T17:33:00.420+0000] {job.py:229} INFO - Heartbeat recovered after 11.90 seconds
[2024-10-14T17:33:40.676+0000] {job.py:229} INFO - Heartbeat recovered after 16.02 seconds
[2024-10-14T17:33:55.964+0000] {job.py:229} INFO - Heartbeat recovered after 18.29 seconds
[2024-10-14T17:33:57.075+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-10-14T17:33:57.300+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-14T17:33:57.531+0000] {process_utils.py:132} INFO - Sending 15 to group 19140. PIDs of all processes in the group: [19140]
[2024-10-14T17:33:57.554+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 19140
[2024-10-14T17:33:58.468+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=19140, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='17:30:54') (19140) terminated with exit code -15
[2024-10-16T14:41:11.765+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-16T14:41:11.872+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-08T00:00:00+00:00 [queued]>
[2024-10-16T14:41:11.900+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-08T00:00:00+00:00 [queued]>
[2024-10-16T14:41:11.902+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-16T14:41:11.982+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ccl_to_redshift> on 2024-09-08 00:00:00+00:00
[2024-10-16T14:41:12.002+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=158) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-16T14:41:12.006+0000] {standard_task_runner.py:72} INFO - Started process 180 to run task
[2024-10-16T14:41:12.008+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_ccl', 'ccl_to_redshift', 'scheduled__2024-09-08T00:00:00+00:00', '--job-id', '382', '--raw', '--subdir', 'DAGS_FOLDER/dag_ccl.py', '--cfg-path', '/tmp/tmphaakbpmu']
[2024-10-16T14:41:12.013+0000] {standard_task_runner.py:105} INFO - Job 382: Subtask ccl_to_redshift
[2024-10-16T14:41:12.149+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-08T00:00:00+00:00 [running]> on host f03003374728
[2024-10-16T14:41:13.034+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ccl' AIRFLOW_CTX_TASK_ID='ccl_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-09-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-08T00:00:00+00:00'
[2024-10-16T14:41:13.037+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-16T14:41:13.070+0000] {logging_mixin.py:190} INFO - 2024-09-08
[2024-10-16T14:41:14.848+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-16T14:41:14.852+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-16T14:41:16.122+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-16T14:41:16.157+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-16T14:41:16.158+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_ccl, task_id=ccl_to_redshift, run_id=scheduled__2024-09-08T00:00:00+00:00, execution_date=20240908T000000, start_date=20241016T144111, end_date=20241016T144116
[2024-10-16T14:41:16.219+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-16T14:41:16.241+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-16T14:41:16.242+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
