[2024-10-14T12:05:19.360+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T12:05:20.041+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-14T12:05:20.247+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-14T12:05:20.261+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-14T12:05:20.610+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-13 00:00:00+00:00
[2024-10-14T12:05:21.175+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14779) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T12:05:21.336+0000] {standard_task_runner.py:72} INFO - Started process 14794 to run task
[2024-10-14T12:05:21.349+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-13T00:00:00+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpz07ho828']
[2024-10-14T12:05:21.649+0000] {standard_task_runner.py:105} INFO - Job 285: Subtask obtener_y_preparar_cotizaciones
[2024-10-14T12:05:22.719+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [running]> on host f03003374728
[2024-10-14T12:05:30.503+0000] {job.py:229} INFO - Heartbeat recovered after 17.74 seconds
[2024-10-14T12:05:41.447+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-13T00:00:00+00:00'
[2024-10-14T12:05:41.985+0000] {job.py:229} INFO - Heartbeat recovered after 12.31 seconds
[2024-10-14T12:05:41.988+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T12:05:42.778+0000] {logging_mixin.py:190} INFO - 2024-10-13
[2024-10-14T12:05:42.788+0000] {logging_mixin.py:190} INFO - 2024-10-14
[2024-10-14T12:05:42.988+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-14T12:05:42.991+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-14T12:05:43.005+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-14T12:05:43.004+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-14T12:05:43.008+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-14T12:05:42.971+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-14T12:05:43.009+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-14T12:05:53.469+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-14T12:05:53.484+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-14T12:05:53.467+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-14T12:05:53.519+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-14T12:05:53.629+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-14T12:05:53.630+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-14T12:05:53.664+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-14T12:05:53.728+0000] {multi.py:184} ERROR - ['BBAR.BA', 'AAPL.BA', 'AMZN.BA', 'PAMP.BA', 'CEPU.BA', 'TGNO4.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-10-13 -> 2024-10-14)')
[2024-10-14T12:05:55.539+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:15: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-14T12:05:56.675+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-14T12:05:56.716+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-14T12:05:59.354+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-14T12:05:59.995+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T12:06:00.038+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-13T00:00:00+00:00, execution_date=20241013T000000, start_date=20241014T120520, end_date=20241014T120600
[2024-10-14T12:06:01.331+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-14T12:06:01.819+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T12:06:01.920+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-15T18:16:28.624+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-15T18:16:28.635+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-15T18:16:28.640+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-15T18:16:28.641+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-15T18:16:28.651+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-13 00:00:00+00:00
[2024-10-15T18:16:28.657+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=858) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-15T18:16:28.658+0000] {standard_task_runner.py:72} INFO - Started process 873 to run task
[2024-10-15T18:16:28.659+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-13T00:00:00+00:00', '--job-id', '368', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmprd86oz7z']
[2024-10-15T18:16:28.661+0000] {standard_task_runner.py:105} INFO - Job 368: Subtask obtener_y_preparar_cotizaciones
[2024-10-15T18:16:28.688+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [running]> on host f03003374728
[2024-10-15T18:16:28.732+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-13T00:00:00+00:00'
[2024-10-15T18:16:28.733+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-15T18:16:28.741+0000] {logging_mixin.py:190} INFO - 2024-10-13
[2024-10-15T18:16:28.741+0000] {logging_mixin.py:190} INFO - 2024-10-14
[2024-10-15T18:16:28.742+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-15T18:16:28.743+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-15T18:16:28.743+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-15T18:16:30.291+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-15T18:16:30.292+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-15T18:16:30.294+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-15T18:16:30.294+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-15T18:16:30.429+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-15T18:16:30.682+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-15T18:16:30.683+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-15T18:16:30.684+0000] {multi.py:184} ERROR - ['AMZN.BA', 'PAMP.BA', 'AAPL.BA', 'CEPU.BA', 'BBAR.BA', 'TGNO4.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-10-13 -> 2024-10-14)')
[2024-10-15T18:16:30.696+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:15: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-15T18:16:30.710+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-15T18:16:30.710+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-15T18:16:31.994+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-15T18:16:32.001+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-15T18:16:32.002+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-13T00:00:00+00:00, execution_date=20241013T000000, start_date=20241015T181628, end_date=20241015T181632
[2024-10-15T18:16:32.034+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-15T18:16:32.047+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-15T18:16:32.047+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
