[2024-10-06T20:29:33.724+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T20:29:33.731+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones manual__2024-10-06T20:24:27.942723+00:00 [queued]>
[2024-10-06T20:29:33.734+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones manual__2024-10-06T20:24:27.942723+00:00 [queued]>
[2024-10-06T20:29:33.734+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-06T20:29:33.739+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-06 20:24:27.942723+00:00
[2024-10-06T20:29:33.743+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1800) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T20:29:33.743+0000] {standard_task_runner.py:72} INFO - Started process 1802 to run task
[2024-10-06T20:29:33.744+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'manual__2024-10-06T20:24:27.942723+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmponkr5kru']
[2024-10-06T20:29:33.746+0000] {standard_task_runner.py:105} INFO - Job 88: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T20:29:33.766+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones manual__2024-10-06T20:24:27.942723+00:00 [running]> on host f03003374728
[2024-10-06T20:29:33.803+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T20:24:27.942723+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-06T20:24:27.942723+00:00'
[2024-10-06T20:29:33.804+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T20:29:33.815+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T20:29:33.815+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T20:29:35.281+0000] {logging_mixin.py:190} INFO - 2024-10-05
[2024-10-06T20:29:35.282+0000] {logging_mixin.py:190} INFO - 2024-10-06
[2024-10-06T20:29:35.287+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:29:35.288+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:29:35.289+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:29:36.664+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:29:36.696+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-06T20:29:36.739+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-06T20:29:36.751+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-06T20:29:36.767+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-06T20:29:36.767+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T20:29:36.776+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T20:29:37.516+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T20:29:37.529+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T20:29:37.530+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=manual__2024-10-06T20:24:27.942723+00:00, execution_date=20241006T202427, start_date=20241006T202933, end_date=20241006T202937
[2024-10-06T20:29:37.565+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T20:29:37.582+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T20:29:37.583+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
