[2024-10-18T00:00:01.407+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-18T00:00:01.417+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.ccl_to_redshift scheduled__2024-10-17T00:00:00+00:00 [queued]>
[2024-10-18T00:00:01.421+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.ccl_to_redshift scheduled__2024-10-17T00:00:00+00:00 [queued]>
[2024-10-18T00:00:01.422+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-18T00:00:01.431+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ccl_to_redshift> on 2024-10-17 00:00:00+00:00
[2024-10-18T00:00:01.435+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1331) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-18T00:00:01.437+0000] {standard_task_runner.py:72} INFO - Started process 1338 to run task
[2024-10-18T00:00:01.437+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'ccl_to_redshift', 'scheduled__2024-10-17T00:00:00+00:00', '--job-id', '477', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpc3uks0ko']
[2024-10-18T00:00:01.443+0000] {standard_task_runner.py:105} INFO - Job 477: Subtask ccl_to_redshift
[2024-10-18T00:00:01.497+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.ccl_to_redshift scheduled__2024-10-17T00:00:00+00:00 [running]> on host f03003374728
[2024-10-18T00:00:01.541+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='ccl_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-17T00:00:00+00:00'
[2024-10-18T00:00:01.542+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-18T00:00:02.482+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-18T00:00:04.538+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-18T00:00:04.550+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-18T00:00:04.551+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=ccl_to_redshift, run_id=scheduled__2024-10-17T00:00:00+00:00, execution_date=20241017T000000, start_date=20241018T000001, end_date=20241018T000004
[2024-10-18T00:00:04.597+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-18T00:00:04.617+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-18T00:00:04.619+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
